"""Generate per-runtime instruction files from the SKILL.md files.

One source of truth. Claude Code reads skills/<name>/SKILL.md directly.
Codex reads AGENTS.md. Gemini CLI reads GEMINI.md. Rather than maintaining
three copies that drift apart, this script derives the other two from the
skills, so a change to a skill reaches every runtime in one commit.

WHAT EACH RUNTIME GETS, AND WHY THEY DIFFER. This script used to compile
all five skill bodies into both files, on the premise that neither runtime
could load a skill. That premise was false for Codex. OpenAI documents
Codex discovering skills from $CWD/.agents/skills, its parents up to
$REPO_ROOT/.agents/skills, and $HOME/.agents/skills, loading them
progressively: name and description first, the body only once the skill is
selected. This repository symlinks .agents/skills to shell/skills, so
Codex already had all five. Copying them into AGENTS.md as well duplicated
them and forced every body into context whether or not it was relevant,
which is the cost progressive disclosure exists to avoid.

So AGENTS.md is lean: the standing rules, the generated command reference,
and a pointer to .agents/skills. GEMINI.md keeps the compiled bodies,
because no equivalent discovery path has been verified for Gemini CLI and
that file is still its whole instruction surface. EMBED_SKILL_BODIES below
is the single switch, so adding a runtime is one entry rather than a
second code path. If Gemini CLI ever grows a documented skills directory,
flip its entry and say so here; do not flip it on an assumption.

Run it from the shell directory:

    python tools/gen_runtime_docs.py

It writes AGENTS.md and GEMINI.md into two places and prints what it wrote:
the shell package, for anyone working inside it, and the repository root,
which is where Codex and Gemini CLI actually look. A copy in only one of
them is a file the runtime never reads.

WHY THIS IMPORTS THE SHELL. The skills are not the whole product. Three
shipped commands (expiries, keys, dashboard) have no skill, so a runtime
that reads only these two files could not learn they exist. The command
reference is therefore read from the argparse parsers the CLI actually
builds rather than typed out here, because a hand-written list is a list
that goes stale the first time a flag is added.

That makes this the one part of the generator that needs the shell package
rather than only files. It does not need it installed: SRC_DIR goes on
sys.path first, so a plain checkout works as long as the CLI import chain
stays standard-library only at import time. When the import fails anyway,
nothing is written and the reason is printed. Writing a file with the
section missing would be worse than writing nothing, because the result
looks complete and is not.
"""

import argparse
import importlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILLS_DIR = ROOT / "skills"
SRC_DIR = ROOT / "src"
CLI_MODULE = "optiondesk.cli.__main__"

HEADER = {
    "AGENTS.md": (
        "# Option desk, instructions for Codex\n\n"
        "This file is generated by {generator} from the "
        "SKILL.md files under {skills}. Edit those, not this file.\n\n"
        "The same capabilities are also exposed over MCP by "
        "`optiondesk-mcp`, which is the preferred path when the runtime "
        "supports it. The command line below is the fallback.\n"),
    "GEMINI.md": (
        "# Option desk, instructions for Gemini CLI\n\n"
        "This file is generated by {generator} from the "
        "SKILL.md files under {skills}. Edit those, not this file.\n\n"
        "The same capabilities are also exposed over MCP by "
        "`optiondesk-mcp`, which is the preferred path when the runtime "
        "supports it. The command line below is the fallback.\n"),
}

# Which runtimes get the skill bodies copied into their file. Codex does
# not, because it loads them itself from .agents/skills; Gemini CLI does,
# because nothing equivalent has been verified for it. See the module
# docstring for the evidence behind each entry.
EMBED_SKILL_BODIES = {"AGENTS.md": False, "GEMINI.md": True}

# How the next section refers back to whatever the file just showed: five
# full sections in GEMINI.md, five names in AGENTS.md. One string cannot be
# accurate in both, and "above" pointing at something that is not there is
# how a generated file starts lying about itself.
SKILLS_LEAD = {"AGENTS.md": "The skills listed above",
               "GEMINI.md": "The skills above"}

SURFACES = (
    "\n## What else is here\n\n"
    "{lead} are the knowledge. The capabilities they describe are "
    "reachable four other ways, all calling the same commands: the command "
    "line (`optiondesk --help`), the MCP server (`optiondesk-mcp`, ten typed "
    "tools), the LangChain bindings in the optional `optiondesk-agent` "
    "package, and a bounded LangGraph routine in that same package "
    "(`open_desk`).\n\n"
    "Two commands are shaped for repetition rather than a single answer. "
    "`/desk-watch` refreshes an underlying and reports only material change. "
    "`/desk-complete` drives the artifact set to completeness against six "
    "criteria that can be checked without judgement. LOOPS.md at the "
    "repository root explains when to use each and what makes a poor loop "
    "here.\n\n"
    "Full catalogue in docs/CAPABILITIES.md, generated public API in "
    "docs/INVENTORY.md, install paths in INSTALL.md.\n")

FOOTER = (
    "\n## Standing rules for every runtime\n\n"
    "Report the `degraded` flag and its reason before any number when it is "
    "true. Never substitute a default implied volatility for a contract that "
    "has none; those contracts are skipped and counted on purpose. Option "
    "premiums are model values from delayed third-party data, not tradable "
    "quotes. Nothing here is investment advice, a recommendation or a "
    "solicitation. See DISCLAIMER.md at the repository root.\n")


def parse_skill(path):
    """Split a SKILL.md into its frontmatter fields and its body."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        raise ValueError("{}: missing YAML frontmatter".format(path))
    _, frontmatter, body = text.split("---", 2)
    fields = {}
    key = None
    for line in frontmatter.strip().splitlines():
        if line and not line.startswith((" ", "\t")) and ":" in line:
            key, _, value = line.partition(":")
            key = key.strip()
            value = value.strip()
            # A description containing a colon has to be quoted to be valid
            # YAML, and the quotes are syntax rather than content. This
            # parser is a line splitter by design, so it strips them here;
            # the frontmatter is separately checked against a real YAML
            # parser by the test suite.
            if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
                value = value[1:-1].replace('\\"', '"').replace("\\\\", "\\")
            fields[key] = value
        elif key:
            fields[key] += " " + line.strip()
    for required in ("name", "description"):
        if required not in fields:
            raise ValueError("{}: frontmatter has no {}".format(path,
                                                                required))
    return fields, body.strip()


def skill_sections(skills):
    """(name, section) for each skill, as it appears in a compiled file.

    Built here rather than inline so the pointer can measure exactly the
    text it is replacing. A number quoted from memory in a generated file
    is a number that goes stale the first time a skill is edited.
    """
    sections = []
    for path in skills:
        fields, body = parse_skill(path)
        sections.append((fields["name"],
                         "\n---\n\n## Skill: {}\n\n{}\n\n{}\n".format(
                             fields["name"], fields["description"], body)))
    return sections


def skills_pointer(skills, prefix):
    """Where the skills are, for a runtime that loads them on its own.

    A file that drops the bodies has to say where they went, or its reader
    is worse off than before: no skills and no pointer either. The names
    are listed because they cost almost nothing and let a reader see the
    whole set at a glance; the bodies are not, because Codex reads those
    itself once it has picked one.

    The `.agents/skills` path is deliberately not prefixed the way the
    others are. It is resolved against the repository root by Codex rather
    than against this file, so it is the same string in both copies, and
    the sentence says so to stop someone "fixing" it into a relative path.

    Nothing here hardcodes how many skills there are, and the heading says
    no number. A count written into generated prose is wrong the day a
    sixth skill lands, and the list beside it would contradict it.
    "resolves to" rather than "is a symlink to" for the same reason: the
    link could become a real directory without the sentence becoming false.
    """
    sections = skill_sections(skills)
    saved = sum(len(section.encode("utf-8")) for _name, section in sections)
    parts = ["\n## The skills, which you load yourself\n\n",
             "They are not copied into this file. You discover skills in "
             "`.agents/skills`, scanning from the working directory up to "
             "the repository root, and read a skill's body only once you "
             "have selected it. Here `.agents/skills` resolves to "
             "`{}skills/`, so all of these are already available to "
             "you:\n\n".format(prefix)]
    for name, _section in sections:
        parts.append("- `{}`\n".format(name))
    parts.append(
        "\nCompiling their bodies into this file as well would add about "
        "{} KB to every session, relevant or not, which is the cost "
        "progressive disclosure exists to avoid. Read the one you need "
        "from `.agents/skills/<name>/SKILL.md`. That path is relative to "
        "the repository root, where you resolve it, not to this "
        "file.\n".format(round(saved / 1024)))
    return "".join(parts)


def load_parser():
    """The parser the CLI builds, or the reason it could not be had.

    Returns (parser, None) or (None, reason). Never raises: this runs for
    people who have cloned the repository and installed nothing, and a
    traceback out of a documentation generator tells them nothing they can
    act on.
    """
    if SRC_DIR.is_dir() and str(SRC_DIR) not in sys.path:
        sys.path.insert(0, str(SRC_DIR))
    try:
        module = importlib.import_module(CLI_MODULE)
    except Exception as exc:
        return None, "cannot import {} ({}: {})".format(
            CLI_MODULE, type(exc).__name__, exc)
    builder = getattr(module, "build_parser", None)
    if builder is None:
        return None, "{} defines no build_parser()".format(CLI_MODULE)
    try:
        return builder(), None
    except Exception as exc:
        return None, "{}.build_parser() failed ({}: {})".format(
            CLI_MODULE, type(exc).__name__, exc)


def subcommands(parser):
    """Every subcommand as (name, help, subparser), in registration order.

    argparse offers no public way to walk a parser, so this reads the
    private attributes. Their shape has been stable across the 3.x series,
    and a change to it would empty the section, which the test catches by
    asserting the parser's own command names against both files on disk.
    """
    for action in parser._actions:
        if not isinstance(action, argparse._SubParsersAction):
            continue
        helps = {entry.dest: entry.help or ""
                 for entry in action._choices_actions}
        for name, sub in action.choices.items():
            yield name, helps.get(name, ""), sub


def usage_line(name, sub):
    """The command and its positional arguments, as a person types them."""
    parts = [name]
    for action in sub._actions:
        if action.option_strings:
            continue
        if action.choices:
            token = "{" + ",".join(str(choice)
                                   for choice in action.choices) + "}"
        else:
            token = action.metavar or action.dest.upper()
        if action.nargs in ("?", "*"):
            token = "[" + token + "]"
        parts.append(token)
    return " ".join(parts)


def flag_names(sub):
    """The long form of every flag on one subcommand, help aside."""
    return [max(action.option_strings, key=len)
            for action in sub._actions
            if action.option_strings and action.dest != "help"]


def command_reference(parser, prefix=""):
    """One entry per subcommand: how to type it, what it does, its flags.

    Deliberately not a manual. Flags are named and not explained, because
    a runtime file long enough to be a reference work stops being read,
    and `optiondesk <command> --help` already prints the full text.
    """
    parts = ["\n## Command reference\n\n",
             "Every command the CLI exposes, read from the argparse parsers "
             "in {}src/optiondesk/cli/ when this file was generated, so it "
             "cannot name a command that does not exist or miss one that "
             "does. Flags are listed, not explained: run `optiondesk "
             "<command> --help` for the detail of any one of "
             "them.\n\n".format(prefix)]
    for name, help_text, sub in subcommands(parser):
        parts.append("- `optiondesk {}`{}\n".format(
            usage_line(name, sub), ": " + help_text if help_text else ""))
        flags = flag_names(sub)
        if flags:
            parts.append("  Flags: {}\n".format(", ".join(flags)))
    return "".join(parts)


def generate(filename, root=None, parser=None):
    """The text of one runtime file, with paths relative to where it lands.

    The header names the generator and the skills directory so a reader can
    find them. Those two paths differ depending on which copy is being
    read: from inside the shell package they are tools/ and skills/, and
    from the repository root they are shell/tools/ and shell/skills/. A
    single hardcoded string is therefore correct in one copy and wrong in
    the other, which is what it was. The command reference carries the same
    problem and takes the same prefix.

    Whether the skill bodies are compiled in is per file, from
    EMBED_SKILL_BODIES: Codex loads them itself from .agents/skills and
    gets a pointer, Gemini CLI has no verified equivalent and gets the
    bodies. Everything else in the two files is identical by construction,
    which is the point of generating them together.
    """
    skills = sorted(SKILLS_DIR.glob("*/SKILL.md"))
    if not skills:
        raise SystemExit("no SKILL.md files found under {}".format(SKILLS_DIR))
    if parser is None:
        parser, reason = load_parser()
        if parser is None:
            raise SystemExit("cannot generate {}: {}".format(filename, reason))
    root = Path(root) if root else ROOT
    prefix = "" if root == ROOT else "{}/".format(ROOT.name)
    parts = [HEADER[filename].format(
        generator="{}tools/gen_runtime_docs.py".format(prefix),
        skills="{}skills/".format(prefix))]
    if EMBED_SKILL_BODIES[filename]:
        parts.extend(section for _name, section in skill_sections(skills))
    else:
        parts.append(skills_pointer(skills, prefix))
    parts.append(SURFACES.format(lead=SKILLS_LEAD[filename]))
    parts.append(command_reference(parser, prefix))
    parts.append(FOOTER)
    return "".join(parts)


def targets(filename):
    """Where this file has to exist to be read.

    Codex and Gemini CLI look for their instruction file in the working
    directory and upward from it, so a copy that lives only inside the
    shell package is never loaded by anyone who opened the repository at
    its root. Both copies are generated from the same text in the same run,
    so there is nothing to drift.
    """
    return [ROOT / filename, ROOT.parent / filename]


def main(argv=None):
    # Resolved once, before anything is written, so a tree where the shell
    # cannot be imported leaves the existing files alone instead of being
    # half rewritten without their command reference.
    parser, reason = load_parser()
    if parser is None:
        print("nothing written: {}".format(reason), file=sys.stderr)
        print("the command reference is read from the CLI parser, so "
              "{} has to be importable".format(SRC_DIR), file=sys.stderr)
        return 1
    written = []
    for filename in HEADER:
        sizes = []
        for target in targets(filename):
            text = generate(filename, root=target.parent, parser=parser)
            target.write_text(text, encoding="utf-8")
            sizes.append(len(text.encode("utf-8")))
        written.append("{} ({} bytes, {} copies)".format(
            filename, max(sizes), len(sizes)))
    print("generated: " + ", ".join(written))
    return 0


if __name__ == "__main__":
    sys.exit(main())
