"""Generate per-runtime instruction files from the SKILL.md files.

One source of truth. Claude Code reads skills/<name>/SKILL.md directly.
Codex reads AGENTS.md. Gemini CLI reads GEMINI.md. Rather than maintaining
three copies that drift apart, this script derives the other two from the
skills, so a change to a skill reaches every runtime in one commit.

Run it from the shell directory:

    python tools/gen_runtime_docs.py

It rewrites AGENTS.md and GEMINI.md in place and prints what it wrote.
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILLS_DIR = ROOT / "skills"

HEADER = {
    "AGENTS.md": (
        "# Option desk, instructions for Codex\n\n"
        "This file is generated by tools/gen_runtime_docs.py from the "
        "SKILL.md files under skills/. Edit those, not this file.\n\n"
        "The same capabilities are also exposed over MCP by "
        "`optiondesk-mcp`, which is the preferred path when the runtime "
        "supports it. The command line below is the fallback.\n"),
    "GEMINI.md": (
        "# Option desk, instructions for Gemini CLI\n\n"
        "This file is generated by tools/gen_runtime_docs.py from the "
        "SKILL.md files under skills/. Edit those, not this file.\n\n"
        "The same capabilities are also exposed over MCP by "
        "`optiondesk-mcp`, which is the preferred path when the runtime "
        "supports it. The command line below is the fallback.\n"),
}

FOOTER = (
    "\n## Standing rules for every runtime\n\n"
    "Report the `degraded` flag and its reason before any number when it is "
    "true. Never substitute a default implied volatility for a contract that "
    "has none; those contracts are skipped and counted on purpose. Option "
    "premiums are model values from delayed third-party data, not tradable "
    "quotes. Nothing here is investment advice, a recommendation or a "
    "solicitation. See DISCLAIMER.md at the repository root.\n")


def parse_skill(path):
    """Split a SKILL.md into its frontmatter fields and its body."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        raise ValueError("{}: missing YAML frontmatter".format(path))
    _, frontmatter, body = text.split("---", 2)
    fields = {}
    key = None
    for line in frontmatter.strip().splitlines():
        if line and not line.startswith((" ", "\t")) and ":" in line:
            key, _, value = line.partition(":")
            key = key.strip()
            fields[key] = value.strip()
        elif key:
            fields[key] += " " + line.strip()
    for required in ("name", "description"):
        if required not in fields:
            raise ValueError("{}: frontmatter has no {}".format(path,
                                                                required))
    return fields, body.strip()


def generate(filename):
    skills = sorted(SKILLS_DIR.glob("*/SKILL.md"))
    if not skills:
        raise SystemExit("no SKILL.md files found under {}".format(SKILLS_DIR))
    parts = [HEADER[filename]]
    for path in skills:
        fields, body = parse_skill(path)
        parts.append("\n---\n\n## Skill: {}\n\n{}\n\n{}\n".format(
            fields["name"], fields["description"], body))
    parts.append(FOOTER)
    return "".join(parts)


def main(argv=None):
    written = []
    for filename in HEADER:
        target = ROOT / filename
        target.write_text(generate(filename), encoding="utf-8")
        written.append("{} ({} bytes)".format(filename,
                                              target.stat().st_size))
    print("generated: " + ", ".join(written))
    return 0


if __name__ == "__main__":
    sys.exit(main())
