"""Generate per-runtime instruction files from the SKILL.md files.

One source of truth. Claude Code reads skills/<name>/SKILL.md directly.
Codex reads AGENTS.md. Gemini CLI reads GEMINI.md. Rather than maintaining
three copies that drift apart, this script derives the other two from the
skills, so a change to a skill reaches every runtime in one commit.

Run it from the shell directory:

    python tools/gen_runtime_docs.py

It writes AGENTS.md and GEMINI.md into two places and prints what it wrote:
the shell package, for anyone working inside it, and the repository root,
which is where Codex and Gemini CLI actually look. A copy in only one of
them is a file the runtime never reads.

WHY THIS IMPORTS THE SHELL. The skills are not the whole product. Three
shipped commands (expiries, keys, dashboard) have no skill, so a runtime
that reads only these two files could not learn they exist. The command
reference is therefore read from the argparse parsers the CLI actually
builds rather than typed out here, because a hand-written list is a list
that goes stale the first time a flag is added.

That makes this the one part of the generator that needs the shell package
rather than only files. It does not need it installed: SRC_DIR goes on
sys.path first, so a plain checkout works as long as the CLI import chain
stays standard-library only at import time. When the import fails anyway,
nothing is written and the reason is printed. Writing a file with the
section missing would be worse than writing nothing, because the result
looks complete and is not.
"""

import argparse
import importlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILLS_DIR = ROOT / "skills"
SRC_DIR = ROOT / "src"
CLI_MODULE = "optiondesk.cli.__main__"

HEADER = {
    "AGENTS.md": (
        "# Option desk, instructions for Codex\n\n"
        "This file is generated by {generator} from the "
        "SKILL.md files under {skills}. Edit those, not this file.\n\n"
        "The same capabilities are also exposed over MCP by "
        "`optiondesk-mcp`, which is the preferred path when the runtime "
        "supports it. The command line below is the fallback.\n"),
    "GEMINI.md": (
        "# Option desk, instructions for Gemini CLI\n\n"
        "This file is generated by {generator} from the "
        "SKILL.md files under {skills}. Edit those, not this file.\n\n"
        "The same capabilities are also exposed over MCP by "
        "`optiondesk-mcp`, which is the preferred path when the runtime "
        "supports it. The command line below is the fallback.\n"),
}

SURFACES = (
    "\n## What else is here\n\n"
    "The skills above are the knowledge. The capabilities they describe are "
    "reachable four other ways, all calling the same commands: the command "
    "line (`optiondesk --help`), the MCP server (`optiondesk-mcp`, ten typed "
    "tools), the LangChain bindings in the optional `optiondesk-agent` "
    "package, and a bounded LangGraph routine in that same package "
    "(`open_desk`).\n\n"
    "Two commands are shaped for repetition rather than a single answer. "
    "`/desk-watch` refreshes an underlying and reports only material change. "
    "`/desk-complete` drives the artifact set to completeness against six "
    "criteria that can be checked without judgement. LOOPS.md at the "
    "repository root explains when to use each and what makes a poor loop "
    "here.\n\n"
    "Full catalogue in docs/CAPABILITIES.md, generated public API in "
    "docs/INVENTORY.md, install paths in INSTALL.md.\n")

FOOTER = (
    "\n## Standing rules for every runtime\n\n"
    "Report the `degraded` flag and its reason before any number when it is "
    "true. Never substitute a default implied volatility for a contract that "
    "has none; those contracts are skipped and counted on purpose. Option "
    "premiums are model values from delayed third-party data, not tradable "
    "quotes. Nothing here is investment advice, a recommendation or a "
    "solicitation. See DISCLAIMER.md at the repository root.\n")


def parse_skill(path):
    """Split a SKILL.md into its frontmatter fields and its body."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        raise ValueError("{}: missing YAML frontmatter".format(path))
    _, frontmatter, body = text.split("---", 2)
    fields = {}
    key = None
    for line in frontmatter.strip().splitlines():
        if line and not line.startswith((" ", "\t")) and ":" in line:
            key, _, value = line.partition(":")
            key = key.strip()
            fields[key] = value.strip()
        elif key:
            fields[key] += " " + line.strip()
    for required in ("name", "description"):
        if required not in fields:
            raise ValueError("{}: frontmatter has no {}".format(path,
                                                                required))
    return fields, body.strip()


def load_parser():
    """The parser the CLI builds, or the reason it could not be had.

    Returns (parser, None) or (None, reason). Never raises: this runs for
    people who have cloned the repository and installed nothing, and a
    traceback out of a documentation generator tells them nothing they can
    act on.
    """
    if SRC_DIR.is_dir() and str(SRC_DIR) not in sys.path:
        sys.path.insert(0, str(SRC_DIR))
    try:
        module = importlib.import_module(CLI_MODULE)
    except Exception as exc:
        return None, "cannot import {} ({}: {})".format(
            CLI_MODULE, type(exc).__name__, exc)
    builder = getattr(module, "build_parser", None)
    if builder is None:
        return None, "{} defines no build_parser()".format(CLI_MODULE)
    try:
        return builder(), None
    except Exception as exc:
        return None, "{}.build_parser() failed ({}: {})".format(
            CLI_MODULE, type(exc).__name__, exc)


def subcommands(parser):
    """Every subcommand as (name, help, subparser), in registration order.

    argparse offers no public way to walk a parser, so this reads the
    private attributes. Their shape has been stable across the 3.x series,
    and a change to it would empty the section, which the test catches by
    asserting the parser's own command names against both files on disk.
    """
    for action in parser._actions:
        if not isinstance(action, argparse._SubParsersAction):
            continue
        helps = {entry.dest: entry.help or ""
                 for entry in action._choices_actions}
        for name, sub in action.choices.items():
            yield name, helps.get(name, ""), sub


def usage_line(name, sub):
    """The command and its positional arguments, as a person types them."""
    parts = [name]
    for action in sub._actions:
        if action.option_strings:
            continue
        if action.choices:
            token = "{" + ",".join(str(choice)
                                   for choice in action.choices) + "}"
        else:
            token = action.metavar or action.dest.upper()
        if action.nargs in ("?", "*"):
            token = "[" + token + "]"
        parts.append(token)
    return " ".join(parts)


def flag_names(sub):
    """The long form of every flag on one subcommand, help aside."""
    return [max(action.option_strings, key=len)
            for action in sub._actions
            if action.option_strings and action.dest != "help"]


def command_reference(parser, prefix=""):
    """One entry per subcommand: how to type it, what it does, its flags.

    Deliberately not a manual. Flags are named and not explained, because
    a runtime file long enough to be a reference work stops being read,
    and `optiondesk <command> --help` already prints the full text.
    """
    parts = ["\n## Command reference\n\n",
             "Every command the CLI exposes, read from the argparse parsers "
             "in {}src/optiondesk/cli/ when this file was generated, so it "
             "cannot name a command that does not exist or miss one that "
             "does. Flags are listed, not explained: run `optiondesk "
             "<command> --help` for the detail of any one of "
             "them.\n\n".format(prefix)]
    for name, help_text, sub in subcommands(parser):
        parts.append("- `optiondesk {}`{}\n".format(
            usage_line(name, sub), ": " + help_text if help_text else ""))
        flags = flag_names(sub)
        if flags:
            parts.append("  Flags: {}\n".format(", ".join(flags)))
    return "".join(parts)


def generate(filename, root=None, parser=None):
    """The text of one runtime file, with paths relative to where it lands.

    The header names the generator and the skills directory so a reader can
    find them. Those two paths differ depending on which copy is being
    read: from inside the shell package they are tools/ and skills/, and
    from the repository root they are shell/tools/ and shell/skills/. A
    single hardcoded string is therefore correct in one copy and wrong in
    the other, which is what it was. The command reference carries the same
    problem and takes the same prefix.
    """
    skills = sorted(SKILLS_DIR.glob("*/SKILL.md"))
    if not skills:
        raise SystemExit("no SKILL.md files found under {}".format(SKILLS_DIR))
    if parser is None:
        parser, reason = load_parser()
        if parser is None:
            raise SystemExit("cannot generate {}: {}".format(filename, reason))
    root = Path(root) if root else ROOT
    prefix = "" if root == ROOT else "{}/".format(ROOT.name)
    parts = [HEADER[filename].format(
        generator="{}tools/gen_runtime_docs.py".format(prefix),
        skills="{}skills/".format(prefix))]
    for path in skills:
        fields, body = parse_skill(path)
        parts.append("\n---\n\n## Skill: {}\n\n{}\n\n{}\n".format(
            fields["name"], fields["description"], body))
    parts.append(SURFACES)
    parts.append(command_reference(parser, prefix))
    parts.append(FOOTER)
    return "".join(parts)


def targets(filename):
    """Where this file has to exist to be read.

    Codex and Gemini CLI look for their instruction file in the working
    directory and upward from it, so a copy that lives only inside the
    shell package is never loaded by anyone who opened the repository at
    its root. Both copies are generated from the same text in the same run,
    so there is nothing to drift.
    """
    return [ROOT / filename, ROOT.parent / filename]


def main(argv=None):
    # Resolved once, before anything is written, so a tree where the shell
    # cannot be imported leaves the existing files alone instead of being
    # half rewritten without their command reference.
    parser, reason = load_parser()
    if parser is None:
        print("nothing written: {}".format(reason), file=sys.stderr)
        print("the command reference is read from the CLI parser, so "
              "{} has to be importable".format(SRC_DIR), file=sys.stderr)
        return 1
    written = []
    for filename in HEADER:
        sizes = []
        for target in targets(filename):
            text = generate(filename, root=target.parent, parser=parser)
            target.write_text(text, encoding="utf-8")
            sizes.append(len(text.encode("utf-8")))
        written.append("{} ({} bytes, {} copies)".format(
            filename, max(sizes), len(sizes)))
    print("generated: " + ", ".join(written))
    return 0


if __name__ == "__main__":
    sys.exit(main())
