#!/usr/bin/env python3
"""Capture the dashboard, panel by panel, from a live run on disk.

WHAT THIS IS. The screenshots in README.md and docs/SCREENSHOTS.md are the
one part of the documentation a reader trusts without reading, and they
were taken by hand, which meant they went stale the moment a panel
changed. This script takes them from a running dashboard, clipping each
image to the element's own bounding box read from the live DOM, so a
panel image is exactly that panel and the set can be regenerated by
anyone with one command.

    python3 scripts/screenshots.py --artifacts /tmp/option-desk-demo \
        --underlying SPY --expiry 2026-10-16

It starts the dashboard from this checkout on a spare port, drives a
headless browser over it, writes the nine README images at a 1400 pixel
viewport and the gallery at 1600, and rewrites docs/SCREENSHOTS.md from
what it captured. Nothing is committed; look at the images first.

Needs Playwright and its Chromium: `pip install playwright` then
`python -m playwright install chromium`. Both are optional for the
project, which is why this is a script rather than a test.
"""

import argparse
import json
import os
import re
import subprocess
import sys
import time
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
GALLERY = DOCS / "screenshots" / "gallery"
README_DIR = DOCS / "screenshots"

# Chart element ids, named the way the gallery names them. An id that is
# not here is captured under its own id, so a new chart is never silently
# dropped.
CHART_NAMES = {
    "gex": "dealer-gamma-by-strike",
    "gexcum": "cumulative-gamma-exposure",
    "oi": "open-interest-by-strike",
    "pain": "max-pain-profile",
    "smile": "implied-volatility-smile",
    "delta": "greek-delta-by-strike",
    "gamma": "greek-gamma-by-strike",
    "vega": "greek-vega-by-strike",
    "theta": "greek-theta-by-strike",
    "vanna": "greek-vanna-by-strike",
    "charm": "greek-charm-by-strike",
    "payoff": "payoff-at-expiry",
    "overlay": "all-structures-on-one-payoff-axis",
    "riskreward": "probability-against-expected-return",
    "fan": "posterior-predictive-fan",
    "terminal": "terminal-distribution",
    "equity": "backtest-equity-curves",
    "drawdown": "backtest-drawdown-from-peak",
    "tradehist": "backtest-trade-outcomes",
    "surface": "implied-volatility-surface",
    "volume": "volume-by-strike",
    "condors": "condor-search",
    "gammascalp": "delta-hedge-corridor",
    "term": "volatility-and-expected-move-by-expiry",
    "skewterm": "skew-across-expiries",
    "vrp": "variance-risk-premium",
}

# The README images: each is the run of elements from one anchor to the
# next, clipped to their union. Anchors are section headings or chart
# ids; "until" is exclusive and names the heading the run stops at.
README_IMAGES = [
    ("dashboard-pipeline", "h2:The pipeline", "h2:Structure comparison"),
    ("dashboard-comparison", "h2:Structure comparison",
     "h2:Composite support"),
    ("dashboard-composite", "h2:Composite support", "h2:Time spreads"),
    ("dashboard-time-spreads", "h2:Time spreads", "h2:Positioning"),
    ("dashboard-positioning", "h2:Positioning", "h2:Volatility"),
    ("dashboard-volatility", "h2:Volatility surface", "id:volume"),
    ("dashboard-structures", "h2:Structures", "h2:The ladder"),
    ("dashboard-ladder", "h2:The ladder", "h2:Condor search"),
    ("dashboard-simulation", "h2:Simulation", "id:gammascalp"),
    ("dashboard-backtest", "h2:Backtest", "h2:Adding data"),
]

# Reads the page once and returns every capture target with its box in
# page coordinates. Sections run from one h2 to the next; panels are the
# .panel elements with an h3 or a chart; charts are the .chart elements.
INVENTORY_SCRIPT = r"""
() => {
  const box = el => { const r = el.getBoundingClientRect();
    return {x: r.left + window.scrollX, y: r.top + window.scrollY,
            width: r.width, height: r.height}; };
  const union = els => {
    const bs = els.map(box).filter(b => b.width > 0 && b.height > 0);
    if (!bs.length) return null;
    const x = Math.min(...bs.map(b => b.x)), y = Math.min(...bs.map(b => b.y));
    const r = Math.max(...bs.map(b => b.x + b.width));
    const d = Math.max(...bs.map(b => b.y + b.height));
    return {x, y, width: r - x, height: d - y};
  };
  const slug = s => s.toLowerCase().replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
  const wrap = document.querySelector('.wrap');
  const kids = Array.from(wrap.children);
  const isH2 = el => el.tagName === 'H2' && el.classList.contains('section');
  const sections = [];
  kids.forEach((el, i) => {
    if (!isH2(el)) return;
    const run = [el];
    for (let j = i + 1; j < kids.length && !isH2(kids[j]); j++) run.push(kids[j]);
    const b = union(run); if (b) sections.push({name: slug(el.textContent), box: b});
  });
  const panels = [];
  const seen = {};
  document.querySelectorAll('.panel').forEach(p => {
    const h3 = p.querySelector('h3');
    let name = h3 ? slug(h3.textContent) : null;
    if (!name) {
      const chart = p.querySelector('.chart');
      if (!chart) return;
      const m = /^dist(\d+)$/.exec(chart.id);
      name = m ? 'profit-distribution-' + (parseInt(m[1], 10) + 1) : chart.id;
    }
    seen[name] = (seen[name] || 0) + 1;
    if (seen[name] > 1) name = name + '-' + seen[name];
    const b = box(p); if (b.height > 0) panels.push({name, box: b});
  });
  const charts = [];
  document.querySelectorAll('.chart').forEach(c => {
    const m = /^dist(\d+)$/.exec(c.id);
    const name = m ? 'profit-distribution-' + (parseInt(m[1], 10) + 1) : c.id;
    const b = box(c); if (b.height > 0) charts.push({id: c.id, name, box: b});
  });
  const anchors = {};
  kids.forEach((el, i) => { if (isH2(el)) anchors['h2:' + el.textContent.trim()] = i; });
  const runs = (from, until) => {
    const start = anchors[from];
    if (start === undefined) return null;
    const els = [];
    for (let j = start; j < kids.length; j++) {
      const el = kids[j];
      if (j > start && until.startsWith('h2:') && isH2(el) && el.textContent.trim() === until.slice(3)) break;
      if (until.startsWith('id:') && el.querySelector('#' + until.slice(3))) break;
      els.push(el);
    }
    return union(els);
  };
  const page = {width: document.documentElement.scrollWidth,
                height: document.documentElement.scrollHeight};
  return {sections, panels, charts, page, runs: null,
          anchors: Object.keys(anchors)};
}
"""

RUN_SCRIPT = r"""
([from, until]) => {
  const box = el => { const r = el.getBoundingClientRect();
    return {x: r.left + window.scrollX, y: r.top + window.scrollY,
            width: r.width, height: r.height}; };
  const union = els => {
    const bs = els.map(box).filter(b => b.width > 0 && b.height > 0);
    if (!bs.length) return null;
    const x = Math.min(...bs.map(b => b.x)), y = Math.min(...bs.map(b => b.y));
    const r = Math.max(...bs.map(b => b.x + b.width));
    const d = Math.max(...bs.map(b => b.y + b.height));
    return {x, y, width: r - x, height: d - y};
  };
  const kids = Array.from(document.querySelector('.wrap').children);
  const isH2 = el => el.tagName === 'H2' && el.classList.contains('section');
  let start = -1;
  kids.forEach((el, i) => {
    if (from.startsWith('h2:') && isH2(el) && el.textContent.trim() === from.slice(3)) start = i;
    if (from.startsWith('id:') && start < 0 && el.querySelector('#' + from.slice(3))) start = i;
  });
  if (start < 0) return null;
  const els = [];
  for (let j = start; j < kids.length; j++) {
    const el = kids[j];
    if (j > start && until.startsWith('h2:') && isH2(el) && el.textContent.trim() === until.slice(3)) break;
    if (j > start && until.startsWith('id:') && el.querySelector('#' + until.slice(3))) break;
    els.push(el);
  }
  return union(els);
}
"""


def wait_for(url, seconds=30):
    deadline = time.time() + seconds
    while time.time() < deadline:
        try:
            with urllib.request.urlopen(url, timeout=2) as response:
                if response.status == 200:
                    return True
        except Exception:
            time.sleep(0.3)
    return False


def start_dashboard(artifacts, port):
    env = dict(os.environ, OPTIONDESK_ARTIFACTS=str(artifacts))
    process = subprocess.Popen(
        [sys.executable, "-m", "optiondesk.cli", "dashboard",
         "--host", "127.0.0.1", "--port", str(port)],
        env=env, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    if not wait_for("http://127.0.0.1:{}/api/status".format(port)):
        process.terminate()
        raise SystemExit("the dashboard did not come up on port {}".format(
            port))
    return process


def clip(page, box, path, page_height):
    """One screenshot clipped to a box, in page coordinates."""
    box = {"x": max(0, box["x"] - 2), "y": max(0, box["y"] - 2),
           "width": box["width"] + 4,
           "height": min(box["height"] + 4, page_height - box["y"] + 2)}
    path.parent.mkdir(parents=True, exist_ok=True)
    page.screenshot(path=str(path), clip=box, full_page=True)
    return path


def capture(url, width, out_dir, readme_dir, readme_width, wait_ms):
    from playwright.sync_api import sync_playwright

    written = {"sections": [], "panels": [], "charts": [], "readme": []}
    with sync_playwright() as playwright:
        browser = playwright.chromium.launch()
        context = browser.new_context(
            viewport={"width": width, "height": 1000},
            device_scale_factor=1, color_scheme="dark")
        page = context.new_page()
        page.goto(url, wait_until="networkidle")
        # ECharts animates for about a second; a capture during that
        # second shows half-drawn axes.
        page.wait_for_timeout(wait_ms)
        inventory = page.evaluate(INVENTORY_SCRIPT)
        height = inventory["page"]["height"]

        full = out_dir / "dashboard-full-page.png"
        full.parent.mkdir(parents=True, exist_ok=True)
        page.screenshot(path=str(full), full_page=True)

        for kind in ("sections", "panels", "charts"):
            for item in inventory[kind]:
                name = item["name"]
                if kind == "charts":
                    name = CHART_NAMES.get(item["id"], name)
                path = clip(page, item["box"],
                            out_dir / kind / "{}.png".format(name), height)
                written[kind].append((name, path))

        context.close()

        # The README images at their own width, so the page reflows the
        # way a reader of GitHub sees it.
        context = browser.new_context(
            viewport={"width": readme_width, "height": 1000},
            device_scale_factor=1, color_scheme="dark")
        page = context.new_page()
        page.goto(url, wait_until="networkidle")
        page.wait_for_timeout(wait_ms)
        height = page.evaluate("document.documentElement.scrollHeight")
        for name, start, until in README_IMAGES:
            box = page.evaluate(RUN_SCRIPT, [start, until])
            if not box:
                print("  skipped {}: {} is not on this page".format(
                    name, start))
                continue
            path = clip(page, box, readme_dir / "{}.png".format(name),
                        height)
            written["readme"].append((name, path))
        context.close()
        browser.close()
    return written


def write_gallery_page(written, run_note):
    def entries(items):
        out = []
        for name, path in sorted(items):
            title = name.replace("-", " ")
            title = title[0].upper() + title[1:]
            relative = path.relative_to(DOCS).as_posix()
            out.append("### {}\n\n![{}]({})\n".format(
                title, name.replace("-", " "), relative))
        return "\n".join(out)

    text = (
        "# Screenshot gallery\n\n"
        "Every panel and every chart the dashboard renders, captured from "
        "one live run by `scripts/screenshots.py`. {}\n\n"
        "Each image is clipped to the element's own bounding box read from "
        "the live DOM, so a panel image is exactly that panel. The images "
        "used in [README.md](../README.md) are in the directory above this "
        "one; this page is the complete set.\n\n"
        "## The whole page\n\n"
        "![The dashboard, top to bottom]"
        "(screenshots/gallery/dashboard-full-page.png)\n\n"
        "## Sections\n\n{}\n"
        "## Panels\n\n{}\n"
        "## Charts\n\n{}".format(
            run_note, entries(written["sections"]),
            entries(written["panels"]), entries(written["charts"])))
    (DOCS / "SCREENSHOTS.md").write_text(text.rstrip() + "\n",
                                         encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--artifacts", required=True,
                        help="artifact directory of the run to capture")
    parser.add_argument("--underlying", default="SPY")
    parser.add_argument("--expiry", default=None)
    parser.add_argument("--port", type=int, default=8799)
    parser.add_argument("--width", type=int, default=1600,
                        help="gallery viewport width")
    parser.add_argument("--readme-width", type=int, default=1400)
    parser.add_argument("--wait-ms", type=int, default=1800)
    parser.add_argument("--note", default="",
                        help="one sentence about the run, for the gallery")
    args = parser.parse_args()

    artifacts = Path(args.artifacts).expanduser().resolve()
    if not artifacts.is_dir():
        raise SystemExit("no such artifact directory: {}".format(artifacts))
    process = start_dashboard(artifacts, args.port)
    try:
        url = "http://127.0.0.1:{}/?u={}".format(args.port, args.underlying)
        if args.expiry:
            url += "&e={}".format(args.expiry)
        written = capture(url, args.width, GALLERY, README_DIR,
                          args.readme_width, args.wait_ms)
    finally:
        process.terminate()
        process.wait(timeout=10)

    write_gallery_page(written, args.note)
    counts = {kind: len(items) for kind, items in written.items()}
    print(json.dumps({"artifacts": str(artifacts), "url": url,
                      "written": counts,
                      "gallery": str(GALLERY.relative_to(ROOT)),
                      "readme_images": [
                          name for name, _ in written["readme"]]},
                     indent=1))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
